# Generated by Django 5.1 on 2024-10-22 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shopdata_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopdata',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_image', to='api.shopimagedata'),
        ),
    ]
