# Generated by Django 5.1 on 2026-06-07 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_shopdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='is_band',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='is_karaoke',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banddata',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='api.eventdata'),
        ),
        migrations.AddField(
            model_name='karaokedata',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karaokes', to='api.eventdata'),
        ),
    ]
