# Generated by Django 5.1 on 2026-06-07 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_eventdata_is_band_eventdata_is_karaoke_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandinspectiondata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='band_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bandsonginspectiondata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='karaokeinspectiondata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karaoke_inspections', to=settings.AUTH_USER_MODEL),
        ),
    ]
