# Generated by Django 5.1 on 2026-06-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bandinspectiondata_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banddata',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bandsongdata',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='karaokedata',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
